#!/bin/sh                                                                                                                  

xrdb $HOME/.Xresources
xsetroot -solid grey
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &                                              
#x-window-manager &                                                                                                        
# Fix to make GNOME work                                                                                                   
export XKL_XMODMAP_DISABLE=1
/etc/X11/Xsession

startxfce4 &

# Start Gnome 3 Desktop                                                                                                    
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
vncconfig -iconic &

#Make prettier                                                                                                             
gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
gnome-terminal &


